[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

#Adds Birthday Cake to cryptid's override file to get it to work like Crustulum
[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "lib/overrides.lua"]'''
pattern = '''if next(find_joker("cry-crustulum")) or G.GAME.current_round.free_rerolls > 0 then'''
position = "before"
payload ='''	if next(find_joker("j_asc_b_cake")) or G.GAME.current_round.free_rerolls > 0 then
		G.GAME.current_round.reroll_cost = 0
		return
	end'''
match_indent = true

#Adds Insanity Mode!!! functionality to cryptid's gateway

[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/exotic.lua"]'''
pattern = '''return #Cryptid.advanced_find_joker(nil, nil, nil, { "eternal" }, true, "j") < G.jokers.config.card_limit'''
position = "at"
payload ='''if not asc_config["Insanity Mode!!!"] or false then
				return #Cryptid.advanced_find_joker(nil, nil, nil, { "eternal" }, true, "j")
					< to_number(G.jokers.config.card_limit)
			else
				return #G.jokers.cards
					< to_number(G.jokers.config.card_limit)
			end
		'''

match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/exotic.lua"]'''
pattern = '''if not v.ability.eternal then'''
position = "at"
payload ='''if not v.ability.eternal and not asc_config["Insanity Mode!!!"] or false then'''
match_indent = true